---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: prod
  labels:
    app: nginx
  specs:
    repkicas: 1
    selector:
      matchLabels:
        app: nginx
    template:
      metadata:
        labels:
          app: nginx
      spec:
        containrs:
          - name: nginx
            image: yakovlopatin/nginx:v0.1.0
            ports:
              - containerPort: 80
